# https://travis-ci.org/#!/clouderp/cerp

dist: bionic

env:
  jobs:
    - ODOO_VERSION=11
    - ODOO_VERSION=12
    - ODOO_VERSION=13

cache:
  directories:
    - /home/travis/build/clouderp/cerp/tmp

install:
  - make travis

script:
  - export COMPOSE_FILE=./composition/docker-compose.yml
  - export ci_env=`bash <(cat tmp/cache/coverage/codecov-env)`
  - >
    docker-compose run
    $ci_env
    -v $(pwd)/tmp/cache/coverage/codecov:/usr/local/bin/codecov
    -v $(pwd)/scripts/send_coverage:/usr/local/bin/send_coverage
    -e COVERAGE_SEND=send_coverage
    --rm web-test
    odoo-test -i keychain2 -i mail
    test cerp_core,cerp_basic,cerp_aws_basic,cerp_azure_basic
  - shellcheck -x scripts/*
  - sudo chown -R travis:travis tmp/cache

deploy:
  provider: script
  script: make release
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(release)$
